# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('categories', models.CharField(max_length=500, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'verbose_name': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='Offerer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('offerer_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Offerers',
                'verbose_name': 'Offerer',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='offerer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.Offerer'),
        ),
    ]
