# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='email',
        ),
        migrations.AddField(
            model_name='offer',
            name='activity_date',
            field=models.DateTimeField(null=True, verbose_name='activity_date'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='published_date'),
        ),
    ]
