# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20161020_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='username',
            new_name='user',
        ),
    ]
