# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20161013_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='username',
            new_name='offerer_name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
