# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20161026_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
