# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20161026_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='maxContacts',
            field=models.IntegerField(default=-1),
        ),
    ]
