# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20161024_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='activity_date',
            field=models.DateTimeField(verbose_name='activity_date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='categories',
            field=models.CharField(default='otros', max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(default='sin descricción', max_length=1000),
        ),
        migrations.AlterField(
            model_name='offer',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(default='sin título', max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='place',
            field=models.CharField(default='sin lugar', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
