# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_offer_maxcontacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='private',
        ),
        migrations.AddField(
            model_name='offer',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
