# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_auto_20161025_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
