# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerer_name',
            field=models.CharField(max_length=200),
        ),
    ]
