# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
